server:
  port: 9090

logging:
  level:
    dev.capybaralabs: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
spring:
  devtools:
    restart:
      additional-paths: "../"
  main:
    banner-mode: log
  output:
    ansi:
      enabled: always
management:
  defaults:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true
