name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          fetch-depth: 0

      - name: Gradle Wrapper Verification
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b # v1.0.4

      - name: Setup JDK
        uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3 # v3.4.1
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Print JDK info
        run: java -Xmx32m --version

      - name: Gradle Assemble
        uses: burrunan/gradle-cache-action@5424817e64ccb6bf267f715f5a46de1bf777c633 # v1.12
        with:
          arguments: clean assemble --info

      - name: Sonarcloud
        uses: burrunan/gradle-cache-action@5424817e64ccb6bf267f715f5a46de1bf777c633 # v1.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          arguments: check sonarqube --no-build-cache --info -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=capybaralabs -Dsonar.login=${{ env.SONAR_TOKEN }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@2a60c5d47eb29cd5cc922f51bbea18e148f56203 # v2.0.0
        if: always()
        with:
          files: ./**/build/test-results/**/*.xml
